### ISSUE TITLE
Sketcher development: Defining-External and general issues

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FPA-grant-proposals#20]
### Proposal description

Sketcher has a lot (345) of opened issues and feature requests.
One outstanding feature request is the ability to have defining external geometries (https://github.com/FreeCAD/FreeCAD/issues/10043).

This proposal is to spend 2 months working on sketcher, specifically on outstanding feature requests and bugs.

### Deliverables

A pull request for each tackled feature requests and bug.

### Timeline

- I can start in january 2025
- I can spend 4 hours 5 days a week for the next 2 months working on this project

### Risks and mitigation

As for any software development, quantifying the amount of work necessary for a specific feature request/bug fix is very difficult. Therefor this proposal is for an undefined amount of goals, but a total amount of time.

### Compensation

My per hour rate being 65€ that would be 5200€/month

### About you

Pierre, paddle on the forum, PaddleStroke on github

In the past I have done a lot of work on sketcher and FreeCAD: https://github.com/FreeCAD/FreeCAD/pulls?q=is%3Apr+author%3APaddleStroke+is%3Aclosed

**Comment by yorikvanhavre** [comment]
This proposal looks fine technically, but the total amount (10400€) is well above the grants the FPA has allocated so far. This might require extra deliberation on the FPA side...

**Comment by PaddleStroke** [comment]
Regarding the compensation I checked online to have an idea of a hourly rate. At first it seemed a bit high to me, but the thing is that this is not an employment, so no holidays, health, retirement, and many taxes to deduct (especially in France). So 10k/month somehow shrinks to something like 4k/month.

Having said that, the question remains that the FPA may not be able to sustainably fund such 'full time' involvment. In which case other solutions could be discussed. First it could start a bit later, since I will have some government help to get by. Also it does not have to be 4h/day on sketcher + 4h/day on assembly, it can be a bit of both or a lot of assembly with some things in sketcher. If in total its 4h/day, I can still get by and do something else aside. Last, I have a small patreon page and I can try to grow. If I can increase this revenu in time, then perhaps it can reach a level where it sustains me by itself.

Perhaps it is time for FPA to accept and ask for coorporate donations? :)

**Comment by prokoudine** [comment]
@PaddleStroke You have to be careful with the Patreon page. If you start using tiers and making patron-only posts and services, it's possible that you can't declare that as donations anymore.

**Comment by Reqrefusion** [comment]
This is a great opportunity for FreeCAD. Such a grant promises a lot for development. However, a total of 8 hours a day seems too much for me (I think the same thing in business life:D) I think a recommendation of 4 hours a day in total would be better. Also, two suggestions are a bit up in the air, for example, what kind of development do you foresee at the end of the first month? I'm curious about both offers.
