### ISSUE TITLE
Assembly development: Top-down design, MbD+FEM ...

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FPA-grant-proposals#21]
### Proposal description

Assembly workbench has some outstanding feature requests such as the support for top-down design, animations (MbD) and there're some very interesting ideas of integrating FEM with MbD to be able to have animated FEM simulations.
On top of that there are some bugs to handle.

This proposal is to spend 2 months working on Assembly, specifically on outstanding feature requests and bugs.

### Deliverables

A pull request for each tackled feature requests and bug.

### Timeline

- I can start in january 2025
- I can spend 4 hours 5 days a week for the next 2 months working on this project

### Risks and mitigation

As for any software development, quantifying the amount of work necessary for a specific feature request/bug fix is very difficult. Therefor this proposal is for an undefined amount of goals, but a total amount of time.

### Compensation

My per hour rate being 65€ that would be 5200€/month

### About you

Pierre, paddle on the forum, PaddleStroke on github

In the past I have done a lot of work on Assembly and FreeCAD: https://github.com/FreeCAD/FreeCAD/pulls?q=is%3Apr+author%3APaddleStroke+is%3Aclosed

**Comment by yorikvanhavre** [comment]
Same comment as #20
