### ISSUE TITLE
Time Commitment Grant Proposal

### ISSUE THREAD

**Issue by bgbsww** [FreeCAD/FPA-grant-proposals#8]
### Proposal description

Continue to address bugs and missing code as discovered in TNP migration.  Develop new code as required to address portions of subshapebinder and sketcher that vary from both the code base at the time of the original TNP branch and from the current Linkstage3 branch.  When no bugs are present, refactor code in Part and PartDesign based on discoveries during the toponaming project.

### Deliverables

Expand TNP mitigation to cover discovered cases.
Address bugs generated by TNP changes

### Timeline

I can start immediately.  I will spend 20-40 hours per week on this project.

### Risks and mitigation

This is a series of small PRs against existing code, and in the event I cannot complete some, the bugs will still be pending for other developers to address.  None of this work should create new major issues; hopefully it will close a lot of bugs before the 1.0 release.

### Compensation

I would like $5000 based on an hourly rate of $50.  Payment after the 100 hours of work are complete would be preferred;  I will report on PR's completed / bugs fixed and time taken.

### About you

Bradley McLean ( bgbsww as an online handle )

I've been working intensively on the Toponaming project for the last six months; I have many [accepted PRs](https://github.com/FreeCAD/FreeCAD/pulls?q=author%3Abgbsww), related to both Toponaming and other FreeCAD bugs.

**Comment by macdroid53** [comment]
Definitely should be accepted.

**Comment by chennes** [comment]
The FPA Grant Review Committee has evaluated this proposal, and supports funding it. bgbsww is clearly the most experienced developer on the Toponaming Mitigation Project, and has deep understanding of the issues at work. His work on the project has been exemplary, and his skills are invaluable in the continuation of the debugging process. I have forwarded this recommendation to the full FPA for voting.

**Comment by chennes** [comment]
The FPA has voted to approve this grant. Congratulations, @bgbsww, and thank you for your proposal.
